# Pandas — Series and DataFrames

> **Repo:** Python_Libraries | **Library:** Pandas  
> **Notebook:** 01_Series_and_DataFrames  

---

## Importing Required Libraries

In [62]:
import pandas as pd
import numpy as np

---
## 1. What is a Series?

A **Series** is a one-dimensional labeled data structure in Pandas.

- 1-dimensional (single column of data)
- Has an **index** (labels) + **values**
- Built on top of a NumPy array
- Can hold any data type (int, float, string, object)
- Mixed types are possible but not recommended

## 2. Creating a Series

### 2.1 From a List
Default integer index is auto-assigned starting from 0.

In [66]:
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

### 2.2 With Custome Index

In [68]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s

a    10
b    20
c    30
dtype: int64

### 2.3 From a NumPy Array
Note: dtype will reflect the NumPy array's dtype (int32 on Windows, int64 on Linux/Mac).

In [70]:
arr = np.array([10,20,30])
s = pd.Series(arr)
s

0    10
1    20
2    30
dtype: int32

### 2.4 With a Custom Data Type
Use `dtype` to explicitly cast values at creation time.

In [72]:
s = pd.Series([1,2,3,4], dtype= 'float')
s

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

### 2.5 From a Dictionary
Keys become the index, values become the data.

In [74]:
students = {'Karan':31, 'Kinnu':29, 'Shanu':28}
s = pd.Series(students)
s

Karan    31
Kinnu    29
Shanu    28
dtype: int64

### 2.6 From a Scalar Value (Broadcasting)
A single value is broadcast across all provided index labels.

In [76]:
s = pd.Series(5, index=['a', 'b', 'c'])
s

a    5
b    5
c    5
dtype: int64

## 3. Series Attributes and Methods

### 3.1 Attributes

In [79]:
s = pd.Series([10, 20, 30, 40])

s.values        # Underlying NumPy array -- array([10, 20, 30, 40], dtype=int64)
s.index         # Index object -- RangeIndex(start=0, stop=4, step=1)
s.dtype         # Data type -- dtype('int64')
s.shape         # Shape (tuple) -- (4,)
s.size          # Number of elements -- 4
s.ndim          # Number of dimensions -- 1
s.empty         # True if no elements -- False
s.name          # Series name -- empty if not named
s.hasnans       # Whether NaN exists -- False if no NaNs..

False

### 3.2 Methods

In [81]:
s.head(2)        # First n elements (default 5)
s.tail(2)        # Last n elements (default 5)
s.describe()     # Summary statistics
s.unique()       # Array of unique values
s.nunique()      # Count of unique values
s.value_counts() # Frequency of each value
s.isnull()       # Boolean mask — True where NaN
s.notnull()      # Boolean mask — True where not NaN
s.sum()          # Sum
s.mean()         # Mean
s.min()          # Minimum value
s.max()          # Maximum value
s.sort_values()  # Sort by value (ascending by default)
s.sort_index()   # Sort by index

0    10
1    20
2    30
3    40
dtype: int64

---
## 4. What is a DataFrame?

A **DataFrame** is a two-dimensional labeled data structure in Pandas.

- Two-dimensional (rows + columns)
- Has a **row index** and a **column index**
- Each column can have a different data type
- Think of it as: **SQL Table + Excel Sheet + NumPy 2D Array**

## 5. Creating a DataFrame

### 5.1 From a Dictionary
Keys become column names, values become column data.

In [85]:
employees = { 'Name': ['Kinnu', 'Bits', 'Shanu'],
                'Salary': [10000, 7500, 5000]
            }

df = pd.DataFrame(employees)
df

    Name  Salary
0  Kinnu   10000
1   Bits    7500
2  Shanu    5000

### 5.2 From a NumPy Array
Column names and index labels can be explicitly provided.

In [87]:
arr = np.array([[1,2],[3,4]])
df = pd.DataFrame(arr, columns=['A','B'], index=['Karan', 'Kanak'])
df

       A  B
Karan  1  2
Kanak  3  4

### 5.3 From a List of Dictionaries
Each dictionary represents one row. Common when working with JSON data or API responses.

In [89]:
data = [{'Name': 'Karan', 'Age': 31},
        {'Name': 'Kinnu', 'Age': 29}]
df = pd.DataFrame(data)
df

    Name  Age
0  Karan   31
1  Kinnu   29

## 6. DataFrame - Attributes and Methods

### 6.1 Attributes

In [92]:
df.shape # Shape of the dataset -- a tuple of rows and columns
df.size # total elements in the dataset -- a number indicating rows * columns
df.ndim # number of dimension -- usually two dimensional
df.columns # A list of columns present in the dataset
df.index # Range of index -- RangeIndex(start=a, stop=z, step=1)
df.dtypes # indicates data type of each column 
df.values # a comprehensive list of all the values present inside the dataset
df.empty # False, if the dataset is not empty
df.T     # Transpose -- changes columns to rows and vice versa
df.axes # returns a list of the axes (row labels and column labels) of the DataFrame.

[RangeIndex(start=0, stop=2, step=1), Index(['Name', 'Age'], dtype='object')]

### 6.2 Methods

In [94]:
df.head() # Display top n rows as you mention, 5 by default
df.tail() # Display bottom n rows as you mention, 5 by default
df.sample(1) # Display any n number of rows as you mention, 1 by default
df.info() # Displays information regarding the DataFrame -- RangeIndex, Data Columns - Names, Non-null Count, dtype, and Memory Usage 
df.describe() # Displays statistical information regarding the numerical columns -- count, mean, std, min, 25%, 50%, 75%, and max
df.describe(include='all') # Include= 'all' takes into consideration all the columns including object, category, datetime
df.nunique # Count of unique values per column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

<bound method DataFrame.nunique of     Name  Age
0  Karan   31
1  Kinnu   29>