# Pandas — Data Selection

> **Repo:** Python_Libraries | **Library:** Pandas  
> **Notebook:** 02_Data_Selection  

---

## Imports

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name":       ["Aarav", "Meera", "Rohan", "Sneha", "Kiran", "Divya"],
    "Age":        [24, 31, 27, 22, 35, 29],
    "City":       ["Mumbai", "Delhi", "Bangalore", "Chennai", "Pune", "Hyderabad"],
    "Department": ["Engineering", "Marketing", "Engineering", "HR", "Finance", "Marketing"],
    "Salary":     [72000, 85000, 68000, 54000, 92000, 78000]
}

df = pd.DataFrame(data)
df

    Name  Age       City   Department  Salary
0  Aarav   24     Mumbai  Engineering   72000
1  Meera   31      Delhi    Marketing   85000
2  Rohan   27  Bangalore  Engineering   68000
3  Sneha   22    Chennai           HR   54000
4  Kiran   35       Pune      Finance   92000
5  Divya   29  Hyderabad    Marketing   78000

## Section 1: Setup & Sample Data

We start by importing Pandas and creating a sample DataFrame that we'll use across all sections.

The dataset represents employee records with the following columns:
- **Name** — Employee name
- **Age** — Employee age
- **City** — City of work
- **Department** — Department they belong to
- **Salary** — Annual salary in INR

## Section 2. Selecting Columns

There are three ways to select columns in pandas.

### 2.1 Bracket Notation -- Single Column -- Returns Series

In [16]:
df['Department']

0    Engineering
1      Marketing
2    Engineering
3             HR
4        Finance
5      Marketing
Name: Department, dtype: object

### 2.2 Multiple Columns -- Returns DataFrame

In [20]:
df[['Name', 'City', 'Salary']]

    Name       City  Salary
0  Aarav     Mumbai   72000
1  Meera      Delhi   85000
2  Rohan  Bangalore   68000
3  Sneha    Chennai   54000
4  Kiran       Pune   92000
5  Divya  Hyderabad   78000

### 2.3 Attribute Access (Not Recommended Professionaly)

In [28]:
df.Name

0    Aarav
1    Meera
2    Rohan
3    Sneha
4    Kiran
5    Divya
Name: Name, dtype: object

## Section 3: Selecting Rows by Position — `iloc`

`iloc` stands for **integer location**.

It lets you select rows (and columns) using their **numeric position**, starting from 0 — just like Python list indexing.

#### Key behaviors:
- `df.iloc[2]` → returns row at position 2 as a **Series**
- `df.iloc[1:4]` → returns rows at positions 1, 2, 3 — **end is exclusive**
- `df.iloc[[0, 2, 5]]` → returns specific rows by passing a list of positions.

> Think of `iloc` as: *"Give me the Nth item"* — pure positional, no labels involved.

In [33]:
# Select a single row by position (returns Series)
df.iloc[2]

Name                Rohan
Age                    27
City            Bangalore
Department    Engineering
Salary              68000
Name: 2, dtype: object

In [48]:
# Select multiple rows by position (returns DataFrame) -- Here, the end point is exclusive
df.iloc[1:4]

    Name  Age       City   Department  Salary
1  Meera   31      Delhi    Marketing   85000
2  Rohan   27  Bangalore  Engineering   68000
3  Sneha   22    Chennai           HR   54000

In [39]:
# Select specific rows by index list
df.iloc[[0, 2, 5]]

    Name  Age       City   Department  Salary
0  Aarav   24     Mumbai  Engineering   72000
2  Rohan   27  Bangalore  Engineering   68000
5  Divya   29  Hyderabad    Marketing   78000

## Section 4: Selecting Rows by Label — `loc`

`loc` stands for **label location**.

It lets you select rows (and columns) using their **index labels** — which in our DataFrame happen to be integers (0, 1, 2...).

#### Key behaviors:
- `df.loc[0]` → returns the row whose **index label** is 0, as a **Series**
- `df.loc[1:3]` → returns rows with labels 1, 2, 3 — **end is inclusive**
- `df.loc[[0, 2, 5]]` → returns specific rows by passing a list of labels
- `df.loc[1:3, ["Name", "Salary"]]` → selects **both rows and columns** together.

> ⚠️ **The critical difference from `iloc`:**

> `iloc[1:4]` → rows 1, 2, 3 (exclusive end — Python style)

> `loc[1:3]` → rows 1, 2, **3** (inclusive end — label style)

In [42]:
# Select a single row by label
df.loc[0]

Name                Aarav
Age                    24
City               Mumbai
Department    Engineering
Salary              72000
Name: 0, dtype: object

In [46]:
# Select a range of rows by label -- here the end point is inclusive
df.loc[1:3]

    Name  Age       City   Department  Salary
1  Meera   31      Delhi    Marketing   85000
2  Rohan   27  Bangalore  Engineering   68000
3  Sneha   22    Chennai           HR   54000

In [50]:
# Select specific rows by label list
df.loc[[0, 2, 5]]

    Name  Age       City   Department  Salary
0  Aarav   24     Mumbai  Engineering   72000
2  Rohan   27  Bangalore  Engineering   68000
5  Divya   29  Hyderabad    Marketing   78000

In [52]:
# Select rows AND specific columns together
df.loc[1:3, ["Name", "Salary"]]

    Name  Salary
1  Meera   85000
2  Rohan   68000
3  Sneha   54000

## Section 5: Boolean / Conditional Filtering

One of the most powerful features in Pandas is the ability to filter rows using conditions.

Instead of loops, you pass a **boolean condition** directly inside `df[...]`

Pandas evaluates it row by row and returns only the rows where the condition is `True`.

### 5.1 Single Condition:

`df[df["Salary"] > 75000]` works in two steps:

1. `df["Salary"] > 75000` → produces a boolean Series (True/False for each row)
2. `df[...]` → uses that Series to filter, keeping only the `True` rows

In [69]:
df[df['Salary'] > 75000]

    Name  Age       City Department  Salary
1  Meera   31      Delhi  Marketing   85000
4  Kiran   35       Pune    Finance   92000
5  Divya   29  Hyderabad  Marketing   78000

### 5.2 Multiple Conditions — `&`, `|`, `~`

When combining conditions, each condition **must be wrapped in parentheses**.

Pandas uses bitwise operators instead of Python's `and` / `or` / `not`:

| Operator | Meaning | Example |
|----------|---------|---------|
| `&` | AND — both conditions must be True | `(df["Age"] > 30) & (df["City"] == "Delhi")` |
| `\|` | OR — at least one condition must be True | `(df["Age"] < 25) \| (df["Salary"] >= 90000)` |
| `~` | NOT — inverts the condition | `~(df["Age"] < 25)` |

In [76]:
df[(df['Age'] > 30) & (df['City'] == 'Delhi')]

    Name  Age   City Department  Salary
1  Meera   31  Delhi  Marketing   85000

In [78]:
df[(df['Age'] < 25) | (df['Salary'] >= 90000)]

    Name  Age     City   Department  Salary
0  Aarav   24   Mumbai  Engineering   72000
3  Sneha   22  Chennai           HR   54000
4  Kiran   35     Pune      Finance   92000

In [84]:
df[~ (df['Age'] < 25)]

    Name  Age       City   Department  Salary
1  Meera   31      Delhi    Marketing   85000
2  Rohan   27  Bangalore  Engineering   68000
4  Kiran   35       Pune      Finance   92000
5  Divya   29  Hyderabad    Marketing   78000

## Section 6: The `.query()` Method

`.query()` is an alternative to boolean filtering that lets you write conditions as a **readable string expression** instead of bracket-heavy syntax.

#### Why use `.query()`?
Compare the two approaches for the same filter:
```python
# Boolean filtering
df[(df["Age"] > 30) & (df["City"] == "Delhi")]

# query()
df.query("Age > 30 & City == 'Delhi'")
```

`.query()` is cleaner and easier to read — especially when conditions stack up.

#### Using variables with `@`
If we have a Python variable we want to reference inside a query string,
prefix it with `@` — this tells Pandas to look it up from the local environment.
```python
min_salary = 80000
df.query("Salary >= @min_salary")
```

#### When to use `.query()` vs boolean filtering?

| Situation | Prefer |
|---|---|
| Quick, readable filters | `.query()` |
| Complex logic or method chaining | `.query()` |
| Filtering with computed values or functions | Boolean filtering |
| Column names with spaces | Boolean filtering |

> 💡 Column names with spaces (e.g., `"First Name"`) don't work cleanly in `.query()`.

> Bracket notation is safer in those cases.

In [91]:
# Same as df[df["Salary"] > 75000]
df.query("Salary > 75000")

    Name  Age       City Department  Salary
1  Meera   31      Delhi  Marketing   85000
4  Kiran   35       Pune    Finance   92000
5  Divya   29  Hyderabad  Marketing   78000

In [93]:
# AND condition
df.query("Age > 30 & City == 'Delhi'")

    Name  Age   City Department  Salary
1  Meera   31  Delhi  Marketing   85000

In [95]:
# Using a variable inside query with @
min_salary = 80000
df.query("Salary >= @min_salary")

    Name  Age   City Department  Salary
1  Meera   31  Delhi  Marketing   85000
4  Kiran   35   Pune    Finance   92000

## Section 7. Selecting Rows and Columns Together

In [103]:
# loc — filter rows by condition, select specific columns
df.loc[df["Department"] == "Engineering", ["Name", "Salary"]]

    Name  Salary
0  Aarav   72000
2  Rohan   68000

In [105]:
# iloc — select rows and columns by position
df.iloc[0:3, 0:3]

    Name  Age       City
0  Aarav   24     Mumbai
1  Meera   31      Delhi
2  Rohan   27  Bangalore

In [109]:
# Combining boolean filter with column selection using query + bracket
df.query("Salary > 75000")[["Name", "Department", "Salary"]]

    Name Department  Salary
1  Meera  Marketing   85000
4  Kiran    Finance   92000
5  Divya  Marketing   78000

## Section 8: Scalar Selection — `at` & `iat`

Sometimes we need to access or update **exactly one value** in a DataFrame.

We could use `loc` or `iloc` for this, but Pandas provides two faster alternatives purpose-built for single scalar access.

| Method | Based on | Syntax |
|---|---|---|
| `at` | Label | `df.at[row_label, "col_name"]` |
| `iat` | Position | `df.iat[row_position, col_position]` |

Think of them as the scalar counterparts to `loc` and `iloc`:
- `at` → `loc` but for one value only
- `iat` → `iloc` but for one value only

### Updating a single value
`at` is the cleanest way to update one cell without affecting the rest of the DataFrame.

`at` is roughly **2.5x faster** than `loc` for scalar access because it skips the overhead of label alignment and multi-axis processing that `loc` handles.

> 💡 **Rule of thumb:**

> - Accessing or updating a **single cell** → use `at` or `iat`
>   
> - Accessing **rows, columns, or slices** → use `loc` or `iloc`

In [112]:
# at — access a single value by row label and column name
df.at[2, "Name"]

'Rohan'

In [114]:
# iat — access a single value by row and column position
df.iat[2, 0]

'Rohan'

In [116]:
# Practical use — updating a single value with at
df.at[2, "Salary"] = 71000
df.loc[[2]]

    Name  Age       City   Department  Salary
2  Rohan   27  Bangalore  Engineering   71000

In [118]:
# Speed comparison context — at/iat vs loc/iloc for scalar access
import timeit

loc_time = timeit.timeit(lambda: df.loc[2, "Salary"], number=10000)
at_time = timeit.timeit(lambda: df.at[2, "Salary"], number=10000)

print(f"loc time : {loc_time:.4f}s")
print(f"at  time : {at_time:.4f}s")

loc time : 0.1891s
at  time : 0.0711s

---
## Summary & Key Takeaways
| Technique | Syntax | Returns |
|---|---|---|
| Single column | `df["col"]` | Series |
| Multiple columns | `df[["col1", "col2"]]` | DataFrame |
| Rows by position | `df.iloc[start:end]` | DataFrame |
| Rows by label | `df.loc[start:end]` | DataFrame |
| Rows + columns (positional) | `df.iloc[rows, cols]` | DataFrame |
| Rows + columns (label) | `df.loc[rows, ["col1"]]` | DataFrame |
| Boolean filter | `df[df["col"] > value]` | DataFrame |
| Multiple conditions | `df[(cond1) & (cond2)]` | DataFrame |
| Query method | `df.query("col > value")` | DataFrame |
| Single scalar (label) | `df.at[row, "col"]` | Scalar |
| Single scalar (position) | `df.iat[row, col]` | Scalar |`, `or`, `not`.**

### The three rules to always remember:
1. **Single brackets `[]` → Series. Double brackets `[[]]` → DataFrame.**
2. **`iloc` end is exclusive. `loc` end is inclusive.**
3. **Always use `&`, `|`, `~` in Pandas filters — never `and`, `or`, `not`.**