# Pandas — Importing & Exporting Data

> **Repo:** Python_Libraries | **Library:** Pandas  
> **Notebook:** 03_Importing_Exporting_Data  

---

## Imports

In [3]:
import pandas as pd
import numpy as np

## Section 1: Reading CSV

The most common way to load data into Pandas is from a CSV file using `pd.read_csv()`.

While the basic usage is simple, `read_csv()` has powerful parameters that let you control exactly how the data is loaded.

### Key parameters covered:

| Parameter | What it does |
|---|---|
| `usecols` | Load only specific columns — saves memory on large files |
| `nrows` | Load only the first N rows — useful for previewing large files |
| `na_values` | Treat custom strings as NaN at import time |
| `index_col` | Set a column as the DataFrame index on load |

In [20]:
# Basic Read
df = pd.read_csv("AB_NYC_2019.csv")
df.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365

In [28]:
# read_csv with key parameters
df = pd.read_csv(
    "AB_NYC_2019.csv",
    usecols=["name", "neighbourhood_group", "room_type", "price", "minimum_nights", "reviews_per_month"],
    nrows=100
)
df.head(3)

,name,neighbourhood_group,room_type,price,minimum_nights,reviews_per_month
0,Clean & quiet apt home by the park,Brooklyn,Private room,149,1,0.21
1,Skylit Midtown Castle,Manhattan,Entire home/apt,225,1,0.38
2,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Private room,150,3,NaN

In [30]:
# Handling missing values at import time
df = pd.read_csv(
    "AB_NYC_2019.csv",
    na_values=["NA", "N/A", "none", ""]
)
df.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365

In [34]:
# Setting a column as index at import time
df = pd.read_csv(
    "AB_NYC_2019.csv",
    index_col="id"
)
df.head(3)

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,,,,,,,,,,,,,,,
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365

In [40]:
df = pd.read_csv("AB_NYC_2019.csv")
df.shape

(48895, 16)

In [44]:
df.columns.tolist()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365']

## Section 2: Reading Excel

For Excel files, Pandas uses `pd.read_excel()` — the syntax is nearly identical to `read_csv()`, but requires an additional engine under the hood.

#### Setup
Excel reading requires the `openpyxl` library (for `.xlsx` files):
```python
!pip install openpyxl
```

#### Key parameters

| Parameter | What it does |
|---|---|
| `usecols` | Load only specific columns |
| `nrows` | Load only the first N rows |
| `sheet_name` | Specify which sheet to read (default is the first sheet) |
| `header` | Row number to use as column names (default is 0) |

In [49]:
# Install required engine for Excel
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\karan\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\karan\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [51]:
# Save our df as Excel first so we have a file to read
df.to_excel("airbnb.xlsx", index=False)

In [ ]:
# Basic Excel read
df_excel = pd.read_excel("airbnb.xlsx")
df_excel.head(3)

In [54]:
# Read specific columns and rows
df_excel = pd.read_excel(
    "airbnb.xlsx",
    usecols=["name", "neighbourhood_group", "room_type", "price"],
    nrows=5
)
df_excel

,name,neighbourhood_group,room_type,price
0,Clean & quiet apt home by the park,Brooklyn,Private room,149
1,Skylit Midtown Castle,Manhattan,Entire home/apt,225
2,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Private room,150
3,Cozy Entire Floor of Brownstone,Brooklyn,Entire home/apt,89
4,Entire Apt: Spacious Studio/Loft by central park,Manhattan,Entire home/apt,80

## Section 3. Reading JSON 

#### What is JSON?
JSON (JavaScript Object Notation) is a lightweight data interchange format that's easy for humans to read and write and easy for machines to parse and generate. It's language-independent but uses conventions familiar to programmers of C-family languages.

#### Key characteristics:

- Text-based format
- Self-describing
- Hierarchical structure
- Commonly used for transmitting data in web applications

#### How JSON Looks Like

JSON data is written as key/value pairs

 Here are examples:

### JSON Structure — Key Concepts

JSON data is built from two structures:
- **Objects** — key/value pairs wrapped in `{}` (like a Python dictionary)
- **Arrays** — ordered lists wrapped in `[]` (like a Python list)

These can be **nested** inside each other to represent hierarchical data.

### The `orient` parameter
`orient` tells Pandas how the JSON is structured:

| orient | Structure |
|---|---|
| `"records"` | List of row objects `[{col: val}, ...]` — most common |
| `"columns"` | Dict of column arrays `{col: {index: val}}` |
| `"index"` | Dict of row dicts `{index: {col: val}}` |
| `"values"` | Just a 2D array of values |

In [66]:
# Basic JSON object
{
  "name": "John Doe",
  "age": 30,
  "city": "New York",
  "isStudent": False
}

{'name': 'John Doe', 'age': 30, 'city': 'New York', 'isStudent': False}

In [68]:
# JSON Array
{
  "employees": [
    {"firstName": "John", "lastName": "Doe"},
    {"firstName": "Anna", "lastName": "Smith"},
    {"firstName": "Peter", "lastName": "Jones"}
  ]
}

{'employees': [{'firstName': 'John', 'lastName': 'Doe'},
  {'firstName': 'Anna', 'lastName': 'Smith'},
  {'firstName': 'Peter', 'lastName': 'Jones'}]}

In [72]:
# Nested JSON
{
  "library": "City Library",
  "books": [
    {
      "title": "Python Basics",
      "author": {
        "name": "Jane Smith",
        "email": "jane@example.com"
      },
      "year": 2020,
      "available": True
    }
  ]
}

{'library': 'City Library',
 'books': [{'title': 'Python Basics',
   'author': {'name': 'Jane Smith', 'email': 'jane@example.com'},
   'year': 2020,
   'available': True}]}

### 3.1 Exporting to JSON

In [75]:
# Save df as JSON first
df.to_json("airbnb.json", orient="records")

### 3.2 Importing JSON

In [78]:
# Basic JSON read
df_json = pd.read_json("airbnb.json")
df_json.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,None,NaN,1,365

In [80]:
# orient parameter -- records is most common for flat data
df_json = pd.read_json("airbnb.json", orient="records")
df_json[["name", "neighbourhood_group", "room_type", "price"]].head(3)

,name,neighbourhood_group,room_type,price
0,Clean & quiet apt home by the park,Brooklyn,Private room,149
1,Skylit Midtown Castle,Manhattan,Entire home/apt,225
2,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Private room,150

## Section 4: Quick Look at the Data

Before doing anything with a dataset, we should always inspect it first.

Following five commands are the standard first-look toolkit in Pandas.

| Method | What it tells you |
|---|---|
| `df.shape` | Dimensions — rows × columns |
| `df.info()` | Column names, dtypes, and non-null counts |
| `df.describe()` | Statistical summary of numeric columns |
| `df.isnull().sum()` | Missing value count per column |
| `df.dtypes` | Data type of each column |

In [85]:
# Shape -- rows and columns
df.shape

(48895, 16)

In [87]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [89]:
# Statistical summary of numeric columns
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [91]:
# Check missing values per column
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [93]:
# Data types of each column
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

## Section 5: Exporting Data

Once we've loaded, cleaned, or transformed our data, we'll often need to export it — to share with teammates, feed into another tool, or save a cleaned version.

Pandas makes this straightforward with `.to_csv()`, `.to_excel()`, and `.to_json()`.

#### Key parameter — `index=False`

By default, Pandas writes the DataFrame index as an extra column in the output.

Almost always we want `index=False` to suppress this — otherwise we'll get an unnamed column of row numbers when the file is reopened.

#### Export methods summary

| Method | Output | Key parameter |
|---|---|---|
| `df.to_csv("file.csv", index=False)` | CSV file | `index`, `sep`, `encoding` |
| `df.to_excel("file.xlsx", sheet_name="Sheet1", index=False)` | Excel file | `sheet_name`, `index` |
| `df.to_json("file.json", orient="records")` | JSON file | `orient` |

In [97]:
# Export to CSV
df.to_csv("airbnb_export.csv", index=False)

In [99]:
# Export specific columns only
df[["name", "neighbourhood_group", "room_type", "price"]].to_csv(
    "airbnb_subset.csv",
    index=False
)

In [101]:
# Export to Excel with sheet name
df.to_excel(
    "airbnb_export.xlsx",
    sheet_name="NYC Listings",
    index=False
)

In [102]:
# Export to JSON
df.to_json("airbnb_export.json", orient="records")