# Pandas — String Operations

> **Repo:** Python_Libraries | **Library:** Pandas  
> **Notebook:** 10_String_Operations  

---

## Section 1: Setup & Creating a Dateset

In [3]:
import pandas as pd
import numpy as np

# Messy customer dataset — intentional inconsistencies for cleaning practice
data = {
    "customer_id": [101, 102, 103, 104, 105, 106],
    "full_name": ["  alice johnson ", "BOB SMITH", "Charlie   Brown", "diana prince  ", "  EVAN WRIGHT", "Fiona green"],
    "email": ["Alice.Johnson@Gmail.COM", "bob.smith@yahoo.com", "CHARLIE@OUTLOOK.COM", "diana@gmail.com", "evan@HOTMAIL.COM", "fiona@gmail.com"],
    "phone": ["98-765-4321", "9123456780", "  91-234-56789  ", "9000011111", "88-888-8888", "7777777777"],
    "city": ["  Mumbai", "delhi", "BANGALORE", "Chennai  ", "hyderabad", "  Pune  "],
    "product_bought": ["Laptop Pro 15", "wireless MOUSE", "USB-C Hub (3-port)", "laptop pro 15", "  Keyboard  ", "wireless mouse"],
    "review": ["Great product!!", "average...not bad", "LOVED IT :)", "good, but expensive.", "  okay okay  ", "Best Buy Ever!!!"]
}

df = pd.DataFrame(data)
df

,customer_id,full_name,email,phone,city,product_bought,review
0,101,alice johnson,Alice.Johnson@Gmail.COM,98-765-4321,Mumbai,Laptop Pro 15,Great product!!
1,102,BOB SMITH,bob.smith@yahoo.com,9123456780,delhi,wireless MOUSE,average...not bad
2,103,Charlie Brown,CHARLIE@OUTLOOK.COM,91-234-56789,BANGALORE,USB-C Hub (3-port),LOVED IT :)
3,104,diana prince,diana@gmail.com,9000011111,Chennai,laptop pro 15,"good, but expensive."
4,105,EVAN WRIGHT,evan@HOTMAIL.COM,88-888-8888,hyderabad,Keyboard,okay okay
5,106,Fiona green,fiona@gmail.com,7777777777,Pune,wireless mouse,Best Buy Ever!!!

## Section 2: Basic Cleaning

In [5]:
# --- Section 2: Basic String Cleaning ---

# 2.1 Strip leading/trailing whitespace
df["full_name"] = df["full_name"].str.strip()
df["city"] = df["city"].str.strip()
df["review"] = df["review"].str.strip()
df["phone"] = df["phone"].str.strip()

# 2.2 Fix casing
df["full_name"] = df["full_name"].str.title()   # Proper Name Format
df["city"] = df["city"].str.title()             # Proper City Format
df["email"] = df["email"].str.lower()           # emails are always lowercase
df["product_bought"] = df["product_bought"].str.strip().str.title()

print("After basic cleaning:\n")
df

After basic cleaning:

,customer_id,full_name,email,phone,city,product_bought,review
0,101,Alice Johnson,alice.johnson@gmail.com,98-765-4321,Mumbai,Laptop Pro 15,Great product!!
1,102,Bob Smith,bob.smith@yahoo.com,9123456780,Delhi,Wireless Mouse,average...not bad
2,103,Charlie Brown,charlie@outlook.com,91-234-56789,Bangalore,Usb-C Hub (3-Port),LOVED IT :)
3,104,Diana Prince,diana@gmail.com,9000011111,Chennai,Laptop Pro 15,"good, but expensive."
4,105,Evan Wright,evan@hotmail.com,88-888-8888,Hyderabad,Keyboard,okay okay
5,106,Fiona Green,fiona@gmail.com,7777777777,Pune,Wireless Mouse,Best Buy Ever!!!

## Section 3: Checking & Detecting

#### 3.1 Which customers used Gmail?

In [8]:
gmail_users = df["email"].str.contains("gmail")
print("Gmail users (boolean):")
print(gmail_users)

print("\nFiltered — Gmail customers only:")
print(df[gmail_users][["customer_id", "full_name", "email"]])

Gmail users (boolean):
0     True
1    False
2    False
3     True
4    False
5     True
Name: email, dtype: bool

Filtered — Gmail customers only:
   customer_id      full_name                    email
0          101  Alice Johnson  alice.johnson@gmail.com
3          104   Diana Prince          diana@gmail.com
5          106    Fiona Green          fiona@gmail.com

#### 3.2 Which names start with a specific letter?

In [10]:
print("\nNames starting with 'A':")
print(df[df["full_name"].str.startswith("A")]["full_name"])

Names starting with 'A':
0    Alice Johnson
Name: full_name, dtype: object

#### 3.3 Which reviews end with '!'?

In [12]:
print("\nEnthusiastic reviews (ending with '!'):")
print(df[df["review"].str.endswith("!")][["full_name", "review"]])

Enthusiastic reviews (ending with '!'):
       full_name            review
0  Alice Johnson   Great product!!
5    Fiona Green  Best Buy Ever!!!

#### 3.4 Are phone numbers all digits?

In [14]:
print("\nIs phone all digits?")
print(df["phone"].str.isdigit())

Is phone all digits?
0    False
1     True
2    False
3     True
4    False
5     True
Name: phone, dtype: bool

## Section 4: Extracting

#### 4.1 Extract first name and last name

In [17]:
df['first_name'] = df['full_name'].str.split().str[0]
df['last_name'] = df['full_name'].str.split().str[1]
print("Full Names splitted in First and Last Name: \n")
print(df[['full_name', 'first_name', 'last_name']])

Full Names splitted in First and Last Name:

         full_name first_name last_name
0    Alice Johnson      Alice   Johnson
1        Bob Smith        Bob     Smith
2  Charlie   Brown    Charlie     Brown
3     Diana Prince      Diana    Prince
4      Evan Wright       Evan    Wright
5      Fiona Green      Fiona     Green

#### 4.2 Extracting Email Domains ( Everything after '@')

In [19]:
df['email_domain'] = df['email'].str.split('@').str[1]
print("\nEmail domains:")
print(df[["email", "email_domain"]])

Email domains:
                     email email_domain
0  alice.johnson@gmail.com    gmail.com
1      bob.smith@yahoo.com    yahoo.com
2      charlie@outlook.com  outlook.com
3          diana@gmail.com    gmail.com
4         evan@hotmail.com  hotmail.com
5          fiona@gmail.com    gmail.com

#### 4.3 Extracting first 3 characters of city as a region code

In [21]:
df['city_code'] = df['city'].str[:3].str.upper()

print("\nCity codes:")
print(df[["city", "city_code"]])

City codes:
        city city_code
0     Mumbai       MUM
1      Delhi       DEL
2  Bangalore       BAN
3    Chennai       CHE
4  Hyderabad       HYD
5       Pune       PUN

#### 4.4 Extract digits only from phone using regex

In [23]:
df["phone_digits"] = df["phone"].str.findall(r"\d+").str.join("")
print("\nFirst digit group extracted from phone:")
print(df[["phone", "phone_digits"]])

First digit group extracted from phone:
          phone phone_digits
0   98-765-4321    987654321
1    9123456780   9123456780
2  91-234-56789   9123456789
3    9000011111   9000011111
4   88-888-8888    888888888
5    7777777777   7777777777

## Section 5: Replacing and Removing

#### 5.1 Fixing Phone Numbers ( Removing all hyphens)

In [26]:
df["phone_clean"] = df['phone'].str.replace("-", "")
print(df[["phone", "phone_clean"]])

          phone phone_clean
0   98-765-4321   987654321
1    9123456780  9123456780
2  91-234-56789  9123456789
3    9000011111  9000011111
4   88-888-8888   888888888
5    7777777777  7777777777

##### Important Note:
In `.str.replace()`, we have one more parameter provided by the pandas, which is `regex=False` ( Default behaviour is False in modern Pandas).

So, we can explicitely use `regex=True` and customize the data with more options. 

Following are the special characters that trigger difference:
> 
. * + ? ^ $ | \ [ ] ( ) { }

Sine your pattern is just a hyphen "-" (not special in regex), both approaches work identically.

#### 5.2 Fixing the USB-C product name using `str.replace()`

In [29]:
df["product_bought"] = df["product_bought"].str.replace("Usb-C", "USB-C")
print(df["product_bought"])

0         Laptop Pro 15
1        Wireless Mouse
2    USB-C Hub (3-Port)
3         Laptop Pro 15
4              Keyboard
5        Wireless Mouse
Name: product_bought, dtype: object

#### 5.3 Remove punctuation from reviews using `regex=True`

In [31]:
df["review_clean"] = df["review"].str.replace(r"[^\w\s]", "", regex=True).str.title()
print(df[["review", "review_clean"]])

                 review        review_clean
0       Great product!!       Great Product
1     average...not bad      Averagenot Bad
2           LOVED IT :)           Loved It
3  good, but expensive.  Good But Expensive
4             okay okay           Okay Okay
5      Best Buy Ever!!!       Best Buy Ever

##### Observation:

The regex pattern: r"[^\w\s]"

- [^...] = Negated character class (match anything NOT listed)
- \w = Word characters (a-z, A-Z, 0-9, _)
- \s = Whitespace (spaces, tabs, newlines)

So [^\w\s] means: match any character that is neither a word character nor whitespace.

#### 5.4 Replace multiple spaces inside strings (e.g. "Charlie   Brown")

In [35]:
df["full_name"] = df["full_name"].str.replace(r"\s+", " ", regex=True).str.strip()

print(df["full_name"])

0    Alice Johnson
1        Bob Smith
2    Charlie Brown
3     Diana Prince
4      Evan Wright
5      Fiona Green
Name: full_name, dtype: object

## Section 6: Splitting and Joining

#### 6.1 Split email into username and domain as separate columns

In [38]:
email_split = df["email"].str.split("@", expand=True)
email_split.columns = ["email_username", "email_domain_full"]
print(email_split)

  email_username email_domain_full
0  alice.johnson         gmail.com
1      bob.smith         yahoo.com
2        charlie       outlook.com
3          diana         gmail.com
4           evan       hotmail.com
5          fiona         gmail.com

##### Note:
`expand= True`: Returns a DataFrame where each split piece become a separate column.

`expand= False` (default behaviour): Returns a Series of Lists.

#### 6.2 Rejoin first_name and last_name with a comma (Last, First format)

In [41]:
df["formal_name"] = df["last_name"] + ", " + df["first_name"]

print(df[["full_name", "formal_name"]])

       full_name     formal_name
0  Alice Johnson  Johnson, Alice
1      Bob Smith      Smith, Bob
2  Charlie Brown  Brown, Charlie
3   Diana Prince   Prince, Diana
4    Evan Wright    Wright, Evan
5    Fiona Green    Green, Fiona

#### 6.3 Concatenate city and email_domain into a contact label using `str.cat()`

In [43]:
df["contact_label"] = df["city"].str.cat(df["email_domain"], sep=" | ")

print(df[["full_name", "city", "email_domain", "contact_label"]])

       full_name       city email_domain            contact_label
0  Alice Johnson     Mumbai    gmail.com       Mumbai | gmail.com
1      Bob Smith      Delhi    yahoo.com        Delhi | yahoo.com
2  Charlie Brown  Bangalore  outlook.com  Bangalore | outlook.com
3   Diana Prince    Chennai    gmail.com      Chennai | gmail.com
4    Evan Wright  Hyderabad  hotmail.com  Hyderabad | hotmail.com
5    Fiona Green       Pune    gmail.com         Pune | gmail.com

## Section 7: String Length and Counting

#### 7.1 Length of each customer's full name

In [46]:
df["name_length"] = df["full_name"].str.len()

print(df[["full_name", "name_length"]])

       full_name  name_length
0  Alice Johnson           13
1      Bob Smith            9
2  Charlie Brown           13
3   Diana Prince           12
4    Evan Wright           11
5    Fiona Green           11

#### 7.2 Word count in each review

In [48]:
df["review_word_count"] = df["review"].str.split().str.len()

print(df[["review", "review_word_count"]])

                 review  review_word_count
0       Great product!!                  2
1     average...not bad                  2
2           LOVED IT :)                  3
3  good, but expensive.                  3
4             okay okay                  2
5      Best Buy Ever!!!                  3

#### 7.3 Count occurrences of a specific character

In [50]:
df["exclamation_count"] = df["review"].str.count(r"!")

print(df[["review", "exclamation_count"]])

                 review  exclamation_count
0       Great product!!                  2
1     average...not bad                  0
2           LOVED IT :)                  0
3  good, but expensive.                  0
4             okay okay                  0
5      Best Buy Ever!!!                  3

#### 7.4 Who wrote the longest and shortest review?

In [52]:
print("\nLongest review:")
print(df.loc[df["review_word_count"].idxmax(), ["full_name", "review"]])

print("\nShortest review:")
print(df.loc[df["review_word_count"].idxmin(), ["full_name", "review"]])

Longest review:
full_name    Charlie Brown
review         LOVED IT :)
Name: 2, dtype: object

Shortest review:
full_name      Alice Johnson
review       Great product!!
Name: 0, dtype: object

##### Observation:
`idxmax/idxmin` picks the FIRST occurrence when there are ties

In [54]:
# Better approach — show ALL longest and shortest reviews

max_words = df["review_word_count"].max()
min_words = df["review_word_count"].min()

print(f"All longest reviews ({max_words} words):")
print(df[df["review_word_count"] == max_words][["full_name", "review"]])

print(f"\nAll shortest reviews ({min_words} words):")
print(df[df["review_word_count"] == min_words][["full_name", "review"]])

All longest reviews (3 words):
       full_name                review
2  Charlie Brown           LOVED IT :)
3   Diana Prince  good, but expensive.
5    Fiona Green      Best Buy Ever!!!

All shortest reviews (2 words):
       full_name             review
0  Alice Johnson    Great product!!
1      Bob Smith  average...not bad
4    Evan Wright          okay okay

## Section 8: Real World Mini Task

In [56]:
data = {
    "emp_id": [201, 202, 203, 204, 205, 206, 207],
    "emp_name": ["  ravi KUMAR ", "Sneha Mehta", "ARJUN das", "priya SHARMA  ", "  Karan Singh", "NEHA joshi  ", "vikram  Bhat"],
    "department": ["  engineering", "MARKETING", "Finance  ", "engineering", "  MARKETING  ", "finance", "Engineering"],
    "email": ["Ravi.Kumar@COMPANY.COM", "sneha.mehta@company.com", "ARJUN@COMPANY.COM", "priya@company.com", "Karan.Singh@Company.Com", "neha@COMPANY.COM", "vikram@company.com"],
    "phone": ["98-765-43210", "9123456780", "  88-888-88888  ", "9000011111", "77-777-77777", "9876543210", "  9111122222"],
    "salary": ["85,000", "72000", "1,10,000", "95,000", "68000", "1,20,000", "76,000"],
    "join_date": ["15-Aug-2019", "2020/03/22", "March 10, 2021", "18-Jan-2018", "2022/07/05", "June 1, 2020", "09-Nov-2017"],
    "performance": ["  excellent  ", "GOOD", "Average", "excellent", "  POOR  ", "good", "  Average  "]
}

df = pd.DataFrame(data)
df

,emp_id,emp_name,department,email,phone,salary,join_date,performance
0,201,ravi KUMAR,engineering,Ravi.Kumar@COMPANY.COM,98-765-43210,"85,000",15-Aug-2019,excellent
1,202,Sneha Mehta,MARKETING,sneha.mehta@company.com,9123456780,72000,2020/03/22,GOOD
2,203,ARJUN das,Finance,ARJUN@COMPANY.COM,88-888-88888,"1,10,000","March 10, 2021",Average
3,204,priya SHARMA,engineering,priya@company.com,9000011111,"95,000",18-Jan-2018,excellent
4,205,Karan Singh,MARKETING,Karan.Singh@Company.Com,77-777-77777,68000,2022/07/05,POOR
5,206,NEHA joshi,finance,neha@COMPANY.COM,9876543210,"1,20,000","June 1, 2020",good
6,207,vikram Bhat,Engineering,vikram@company.com,9111122222,"76,000",09-Nov-2017,Average

#### Tasks to be done:
- emp_name — Strip whitespace, fix to Title Case, collapse internal extra spaces, then split into first_name and last_name
- department — Strip, Title Case, then verify: how many unique departments are there?
- email — Lowercase, then extract email_username (before @) and email_provider (after @) as separate columns
- phone — Strip whitespace, remove hyphens, check which entries are all digits using str.isdigit()
- salary — Remove all commas, convert to integer, then find the highest and lowest paid employee
- join_date — This one is tricky — three different date formats are mixed. Just use pd.to_datetime(df["join_date"], infer_datetime_format=True) and see what happens
- performance — Strip, lowercase, then use str.replace() to create a numeric perf_score column: excellent→4, good→3, average→2, poor→1

#### 8.1 `emp_name`, `first_name`, `last_name`

In [59]:
# Creating an empty DataFrame 
clean_df = pd.DataFrame()

clean_df['emp_name'] = df['emp_name'].str.strip().str.title().str.replace(r"\s+", " ", regex=True)

clean_df['first_name'] = clean_df['emp_name'].str.split(" ").str[0]
clean_df['last_name'] = clean_df['emp_name'].str.split(" ").str[1]

clean_df[['emp_name', 'first_name', 'last_name']]

       emp_name first_name last_name
0    Ravi Kumar       Ravi     Kumar
1   Sneha Mehta      Sneha     Mehta
2     Arjun Das      Arjun       Das
3  Priya Sharma      Priya    Sharma
4   Karan Singh      Karan     Singh
5    Neha Joshi       Neha     Joshi
6   Vikram Bhat     Vikram      Bhat

#### 8.2 `department` & Count of Unique Departments

In [61]:
clean_df['department'] = df['department'].str.strip().str.title()
print(clean_df['department'])

0    Engineering
1      Marketing
2        Finance
3    Engineering
4      Marketing
5        Finance
6    Engineering
Name: department, dtype: object

In [62]:
# Counting the employees inside a department using `value_counts()`
clean_df['department'].value_counts()

department
Engineering    3
Marketing      2
Finance        2
Name: count, dtype: int64

In [63]:
# Counting the number of unique values inside the column department using `nunique()`
clean_df['department'].nunique()

3

In [64]:
# Displaying the unique values inside a colunn using `unique()` 
clean_df['department'].unique()

array(['Engineering', 'Marketing', 'Finance'], dtype=object)

#### 8.3 `email`, `email_username`, `email_provider`

In [107]:
clean_df['email'] = df['email'].str.strip().str.lower()

clean_df['email_username'] = clean_df['email'].str.split('@').str[0]
clean_df['email_provider'] = clean_df['email'].str.split('@').str[1]

#### 8.4 `phone`

In [68]:
# Checking which phone numbers are all digit in messy dataframe
df['phone'].str.isdigit()

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: phone, dtype: bool

In [69]:
# cleaning phone numbers
clean_df['phone'] = df['phone'].str.strip().str.replace('-', '') 
clean_df['phone']

0    9876543210
1    9123456780
2    8888888888
3    9000011111
4    7777777777
5    9876543210
6    9111122222
Name: phone, dtype: object

In [70]:
# Rechecking phone whether all values are digits or not
clean_df['phone'].str.isdigit()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
Name: phone, dtype: bool

#### 8.5 `salary` and Highest & Lowest paid employees

In [72]:
# Checking current value in messy data
df['salary'].str.isdigit()

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: salary, dtype: bool

In [73]:
clean_df['salary'] = df['salary'].str.replace(r"[^\w]", "", regex=True)

clean_df['salary'] = pd.to_numeric(clean_df['salary'])

# sanity check
print(clean_df['salary'].dtype)

int64

In [74]:
# Highest_paid employee
highest_salary = clean_df['salary'].max()

print(clean_df[['emp_name', 'department', 'salary']][clean_df['salary'] == highest_salary])

# also print(clean_df[['emp_name', 'department', 'salary']][clean_df['salary'] == clean_df['salary'].max()])

     emp_name department  salary
5  Neha Joshi    Finance  120000

In [75]:
# Lowest_paid employee
Lowest_salary = clean_df['salary'].min()

print(clean_df[['emp_name', 'department', 'salary']][clean_df['salary'] == Lowest_salary])

# also print(clean_df[['emp_name', 'department', 'salary']][clean_df['salary'] == clean_df['salary'].min()])

      emp_name department  salary
4  Karan Singh  Marketing   68000

#### 8.6 `join_date`

In [77]:
# Checking current datatype of join_date column
print(df['join_date'])

0       15-Aug-2019
1        2020/03/22
2    March 10, 2021
3       18-Jan-2018
4        2022/07/05
5      June 1, 2020
6       09-Nov-2017
Name: join_date, dtype: object

In [78]:
from dateutil import parser

# This handles ALL formats reliably
clean_df['join_date'] = df['join_date'].apply(
    lambda x: parser.parse(x) if pd.notna(x) else pd.NaT
)

clean_df['join_date']

0   2019-08-15
1   2020-03-22
2   2021-03-10
3   2018-01-18
4   2022-07-05
5   2020-06-01
6   2017-11-09
Name: join_date, dtype: datetime64[ns]

#### Interpretation:
```
clean_df['join_date'] = pd.to_datetime(
    df['join_date'],
    errors='coerce'
)

- pd.to_datetime() is vectorized, faster and cleaner but couldn't handle messy dates.
- Therefore, dateutil.parser is being used here.
- In the same way, `pd.to_datetime(df["join_date"], infer_datetime_format=True)` also couldn't handle this messy data and converted most of the dates into NaT.

#### 8.7 `performance` and `perf_score`:

In [109]:
clean_df['performance'] = df['performance'].str.strip().str.lower()

In [103]:
# Creating perf_score based on performance column
clean_df['perf_score'] = clean_df['performance'].map({
                                    'excellent': 4,
                                    'good'     : 3,
                                    'average'  : 2,
                                    'poor'     : 1
}).astype('Int64')

In [111]:
# Final output -- our cleaned DataFrame
clean_df

,emp_name,first_name,last_name,department,email,email_username,email_provider,phone,salary,join_date,performance,perf_score
0,Ravi Kumar,Ravi,Kumar,Engineering,ravi.kumar@company.com,ravi.kumar,company.com,9876543210,85000,2019-08-15,excellent,4
1,Sneha Mehta,Sneha,Mehta,Marketing,sneha.mehta@company.com,sneha.mehta,company.com,9123456780,72000,2020-03-22,good,3
2,Arjun Das,Arjun,Das,Finance,arjun@company.com,arjun,company.com,8888888888,110000,2021-03-10,average,2
3,Priya Sharma,Priya,Sharma,Engineering,priya@company.com,priya,company.com,9000011111,95000,2018-01-18,excellent,4
4,Karan Singh,Karan,Singh,Marketing,karan.singh@company.com,karan.singh,company.com,7777777777,68000,2022-07-05,poor,1
5,Neha Joshi,Neha,Joshi,Finance,neha@company.com,neha,company.com,9876543210,120000,2020-06-01,good,3
6,Vikram Bhat,Vikram,Bhat,Engineering,vikram@company.com,vikram,company.com,9111122222,76000,2017-11-09,average,2